channels:
  - conda-forge
dependencies:
  - defusedxml >=0.5.0
  - coveralls
  - coverage
  - codacy-coverage
  - pandas >=0.24.2
  - pyyaml >=5.1.2
  - jinja2 >=2.10.1
  - paramiko >=2.7.2
  - tqdm >=4.35.0
