channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- defusedxml =0.7.1
- pandas =3.0.0
- pyyaml =6.0.3
- jinja2 =3.1.6
- paramiko =4.0.0
- tqdm =4.67.2
- jupyter-book =1.0.0
- python =3.12
- hatchling =1.28.0
- hatch-vcs =0.5.0
