channels:
- conda-forge
dependencies:
- python =3.13
- defusedxml =0.7.1
- flux-core =0.81.0
- pandas =3.0.0
- pyyaml =6.0.3
- jinja2 =3.1.6
- paramiko =4.0.0
- tqdm =4.67.2
- hatchling =1.28.0
- hatch-vcs =0.5.0
